GET http://localhost:3001/eventos

###

GET http://localhost:3001/eventos/889df5e4-c4f9-4a19-951e-5354184d6453

###

POST http://localhost:3001/eventos
Content-Type: application/json

{
    "nome": "Novo Evento",
    "descricao": "Esse é um novo evento",
    "data": "2017-01-01T00:00:00",
    "preco": 50
}

###

PATCH http://localhost:3001/eventos/889df5e4-c4f9-4a19-951e-5354184d6453
Content-Type: application/json

{
    "nome": "Nova Atualizacao Evento",
    "descricao": "Essa é uma nova atualização evento",
    "data": "2017-01-01T00:00:00",
    "preco": 200
}

###

DELETE http://localhost:3001/eventos/66b95155-a6f1-44b4-b04d-3d62a3a77269

###

###

POST http://localhost:3001/eventos/889df5e4-c4f9-4a19-951e-5354184d6453/reservar
Content-Type: application/json
X-Api-Token: 123

{
    "lugares": ["A1", "A2"],
    "tipo_ingresso": "meia",
    "email": "test@test.com"
}


###
GET http://localhost:3001/eventos/889df5e4-c4f9-4a19-951e-5354184d6453/lugares

###

GET http://localhost:3001/eventos/889df5e4-c4f9-4a19-951e-5354184d6453/lugares/b40165d1-1c85-4177-8369-db1bd6362dfb

###

POST http://localhost:3001/eventos/889df5e4-c4f9-4a19-951e-5354184d6453/lugares
Content-Type: application/json

{
    "nome": "A2"
}

###

PATCH  http://localhost:3001/eventos/889df5e4-c4f9-4a19-951e-5354184d6453/lugares/b906aa25-c05a-4598-b54c-0ebd4a901e8b
Content-Type: application/json

{
    "nome": "B1"
}

###

DELETE http://localhost:3001/eventos/889df5e4-c4f9-4a19-951e-5354184d6453/lugares/b906aa25-c05a-4598-b54c-0ebd4a901e8b

###